import QueryProvider from '@/providers/QueryProvider';
import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React, { PropsWithChildren } from 'react';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const viewport: Viewport = {
    themeColor: 'black',
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    manifest: '/manifest.json',
    icons: {
        icon: '/test_icon.png',
        shortcut: '/test_icon.png',
        apple: '/test_icon.png',
        other: {
            rel: 'apple-touch-icon-precomposed',
            url: '/test_icon.png',
        },
    },
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Script
                    src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js"
                    strategy="beforeInteractive"
                />
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
};

export default RootLayout;
